### ISSUE TITLE
Using RAM in version 2.7.8

### ISSUE THREAD

**Issue by Lokeryt** [HIllya51/LunaTranslator#217]
In the latest version 2.7.8, when using local OCR, over time, the application begins to use more and more RAM, so up to the whole. After that, the windows OCR error appears in the application. I have a black screen and I need to restart my PC. There is no such thing in previous versions

**Comment by HIllya51** [comment]
Are you sure you have updated to the latest version? In version 2.7.7, someone has already reported this issue to me, and I have already fixed it.

**Comment by Lokeryt** [comment]
Yes, it was definitely version 2.7.8, yesterday I downloaded it again and the problem remained. Now I have downloaded v2.7.9 and there is no problem. Thank you for this wonderful app
